function rmsNoise = RawDataNoiseEvaluationM( dataPath, saveFolder )
% RAWDATANOISEEVALUATION Evaluates the amount of noise over all electrodes
% for a input data recording
% Generates and save the output .noise file in ascii single precision
% number - as column array.
%
% Watch for heading tab in each line generated by matlab sav.
%
% Arguments:
% dataPath - absolute or relative path to data folder/file
% saveFolder - absolute or relative path to output save folder
%
%--------------------------------------------

%% Using java up to getData
import edu.ucsc.neurobiology.vision.io.*
import java.io.*

% Hardcoded configuration from the java version
time = 5; % Compute noise from 5 secs of data
timeToSkip = 5; % Skip the first 5 sec of the file

% Setup the data source
dataSource = DataFileUpsampler(dataPath);

header = dataSource.rawDataFile.getHeader();

samplingRate = header.getSamplingFrequency();

nSamples = time * samplingRate;

% getData

dataSource.loadRandomBuffer(timeToSkip * samplingRate + dataSource.startSample, nSamples, false);

%% Starting noise calculation
[rmsNoise,~] = getNoise(dataSource.rawData(2:end,:)); % Skip TTL
rmsNoise = [0;rmsNoise];

%% Writing output .noise file - as .ascii and as .mat
[~,name,~] = fileparts(dataPath); % Catching folder name as last element of saveFolder path
save([saveFolder,filesep,name,'.noise'],'rmsNoise','-ascii','-double'); % Saving, ascii single precision format
save([saveFolder,filesep,name,'.noise.mat'],'rmsNoise'); % Saving a copy in mat format for further use.

end
